### ISSUE TITLE
Support for EXOS

### ISSUE THREAD

**Issue by schlady** [extremenetworks/ansible-extreme#4]
Nice to see upcoming Ansible support from Extreme Networks. I have looked for this feature for some time.
It would be awesome if you could also support EXOS for your EdgeSwitch portfolio (Summit and X series).

**Comment by LindsayHill** [comment]
@schlady would you like to collaborate on writing those? Using the new Ansible `network_cli` plugin takes away some of the lower-level work. 

To get an initial module working, you only need to copy & update these equivalents from the SLXOS modules:

* lib/ansible/module_utils/network/slxos/slxos.py
* lib/ansible/plugins/cliconf/slxos.py
* lib/ansible/plugins/terminal/slxos.py
* lib/ansible/utils/module_docs_fragments/slxos.py

Once you have those in place, it is just a matter of writing the individual modules, e.g. lib/ansible/modules/network/slxos/slxos_command.py

There's plenty of examples out there - e.g. the IOS module - and much of the common functions already exist, they just need minor updates to reflect the differences in CLI.

It's all Open Source, so anyone can contribute. It doesn't have to come from the vendor.

**Comment by LindsayHill** [comment]
Exos command module has been merged to upstream ansible - see https://github.com/ansible/ansible/pull/37775 and https://docs.ansible.com/ansible/devel/modules/exos_command_module.html

This was contributed by another user.
